services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: balance
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d balance -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: balance
      DB_SSLMODE: disable
      SERVER_PORT: "8080"
    restart: on-failure